### ISSUE TITLE
y-axis isn't scaling on radio button press

### ISSUE THREAD

**Issue by fredhohman** [ParametricPress/02-algae#7]
@bendoesdata this chart only has the x-axis updating properly when changing the radio buttons. I've commented out the radio button in 2acee55225bff5854f74a9a47da75f3c7c5ec10c for now, but let's add it back as soon as we can!

![image](https://user-images.githubusercontent.com/5741691/96765848-3d5ef980-13a8-11eb-8799-3fda1a47c5c6.png)

![image](https://user-images.githubusercontent.com/5741691/96765874-451e9e00-13a8-11eb-9b49-7c6c40fc818b.png)

**Comment by bendoesdata** [comment]
Pushed a fix that resolves
